{
  "swagger": "2.0",
  "info": {
    "title": "brainrot API",
    "description": "M4n5ter's brain rot time project",
    "version": "v1.0",
    "contact": {
      "name": "M4n5ter",
      "url": "https://github.com/M4n5ter",
      "email": "m4n5terrr@gmail.com"
    },
    "license": {
      "name": "联系: M4n5ter",
      "url": "https://t.me/M4n5ter"
    }
  },
  "tags": [
    {
      "name": "Ping"
    },
    {
      "name": "User"
    },
    {
      "name": "Article"
    },
    {
      "name": "Comment"
    },
    {
      "name": "S3"
    }
  ],
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/brainrot/article/add-tags": {
      "post": {
        "summary": "添加标签",
        "operationId": "Article_AddTags",
        "responses": {
          "200": {
            "description": "添加成功",
            "schema": {
              "$ref": "#/definitions/v1AddTagsResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "description": "TODO: This operation should be protected by a security mechanism. e.g, only privilege user can do this.",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1AddTagsRequest"
            }
          }
        ],
        "tags": [
          "Article"
        ]
      }
    },
    "/v1/brainrot/article/delete": {
      "post": {
        "summary": "删除一篇文章",
        "operationId": "Article_DeleteArticle",
        "responses": {
          "200": {
            "description": "删除成功",
            "schema": {
              "$ref": "#/definitions/v1DeleteArticleResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1DeleteArticleRequest"
            }
          }
        ],
        "tags": [
          "Article"
        ]
      }
    },
    "/v1/brainrot/article/delete-tag": {
      "post": {
        "summary": "删除标签",
        "operationId": "Article_DeleteTag",
        "responses": {
          "200": {
            "description": "删除成功",
            "schema": {
              "$ref": "#/definitions/v1DeleteTagResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "description": "TODO: This operation should be protected by a security mechanism. e.g, only privilege user can do this.",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1DeleteTagRequest"
            }
          }
        ],
        "tags": [
          "Article"
        ]
      }
    },
    "/v1/brainrot/article/post": {
      "post": {
        "summary": "发布一篇文章",
        "operationId": "Article_PostArticle",
        "responses": {
          "200": {
            "description": "发布成功",
            "schema": {
              "$ref": "#/definitions/v1PostArticleResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1PostArticleRequest"
            }
          }
        ],
        "tags": [
          "Article"
        ]
      }
    },
    "/v1/brainrot/article/refresh-all": {
      "post": {
        "summary": "刷新所有文章",
        "operationId": "Article_RefreshAllArticles",
        "responses": {
          "200": {
            "description": "刷新成功",
            "schema": {
              "$ref": "#/definitions/v1RefreshAllArticlesResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "description": "TODO: This operation should be protected by a security mechanism. e.g, only privilege user can do this.",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1RefreshAllArticlesRequest"
            }
          }
        ],
        "tags": [
          "Article"
        ]
      }
    },
    "/v1/brainrot/comment/delete": {
      "post": {
        "summary": "删除一条评论",
        "operationId": "Comment_DeleteComment",
        "responses": {
          "200": {
            "description": "删除成功",
            "schema": {
              "$ref": "#/definitions/v1DeleteCommentResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1DeleteCommentRequest"
            }
          }
        ],
        "tags": [
          "Comment"
        ]
      }
    },
    "/v1/brainrot/comment/edit": {
      "post": {
        "summary": "编辑一条评论",
        "operationId": "Comment_EditComment",
        "responses": {
          "200": {
            "description": "编辑成功",
            "schema": {
              "$ref": "#/definitions/v1EditCommentResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1EditCommentRequest"
            }
          }
        ],
        "tags": [
          "Comment"
        ]
      }
    },
    "/v1/brainrot/comment/get-by-article": {
      "post": {
        "summary": "获取一篇文章的所有评论",
        "operationId": "Comment_GetCommentsByArticle",
        "responses": {
          "200": {
            "description": "获取成功",
            "schema": {
              "$ref": "#/definitions/v1GetCommentsByArticleResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1GetCommentsByArticleRequest"
            }
          }
        ],
        "tags": [
          "Comment"
        ]
      }
    },
    "/v1/brainrot/comment/post": {
      "post": {
        "summary": "发布一条评论",
        "operationId": "Comment_PostComment",
        "responses": {
          "200": {
            "description": "发布成功",
            "schema": {
              "$ref": "#/definitions/v1PostCommentResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1PostCommentRequest"
            }
          }
        ],
        "tags": [
          "Comment"
        ]
      }
    },
    "/v1/brainrot/comment/update-usefulness": {
      "post": {
        "summary": "更新评论有用性",
        "operationId": "Comment_UpdateCommentUsefulness",
        "responses": {
          "200": {
            "description": "更新成功",
            "schema": {
              "$ref": "#/definitions/v1UpdateCommentUsefulnessResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1UpdateCommentUsefulnessRequest"
            }
          }
        ],
        "tags": [
          "Comment"
        ]
      }
    },
    "/v1/brainrot/ping": {
      "get": {
        "summary": "Ping is a simple health check",
        "operationId": "Ping_Ping",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1PingResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "Ping"
        ]
      }
    },
    "/v1/brainrot/s3/get-presigned-url": {
      "post": {
        "summary": "获取一个 S3 对象的预签名 URL",
        "operationId": "S3_GetPresignedURL",
        "responses": {
          "200": {
            "description": "获取成功",
            "schema": {
              "$ref": "#/definitions/v1GetPresignedURLResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1GetPresignedURLRequest"
            }
          }
        ],
        "tags": [
          "S3"
        ]
      }
    },
    "/v1/brainrot/user/current": {
      "get": {
        "summary": "获取当前用户信息",
        "operationId": "User_GetCurrentUserInfo",
        "responses": {
          "200": {
            "description": "获取成功",
            "schema": {
              "$ref": "#/definitions/v1GetCurrentUserInfoResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "User"
        ]
      }
    },
    "/v1/brainrot/user/refresh-token": {
      "post": {
        "summary": "刷新令牌",
        "operationId": "User_RefreshToken",
        "responses": {
          "200": {
            "description": "刷新令牌成功",
            "schema": {
              "$ref": "#/definitions/v1RefreshTokenResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1RefreshTokenRequest"
            }
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/v1/brainrot/user/search": {
      "post": {
        "summary": "搜索用户",
        "operationId": "User_Search",
        "responses": {
          "200": {
            "description": "搜索成功",
            "schema": {
              "$ref": ".brainrot.v1.SearchUserResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1SearchUsersRequest"
            }
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/v1/brainrot/user/sign-in": {
      "post": {
        "summary": "用户登录",
        "operationId": "User_SignIn",
        "responses": {
          "200": {
            "description": "登录成功",
            "schema": {
              "$ref": "#/definitions/v1SignInResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1SignInRequest"
            }
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/v1/brainrot/user/sign-up": {
      "post": {
        "summary": "将一个用户注册到数据库",
        "operationId": "User_SignUp",
        "responses": {
          "200": {
            "description": "注册成功",
            "schema": {
              "$ref": "#/definitions/v1SignUpResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "description": "用户注册请求体",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1SignUpRequest"
            }
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/v1/brainrot/user/update": {
      "post": {
        "summary": "更新用户信息",
        "operationId": "User_Update",
        "responses": {
          "200": {
            "description": "更新成功",
            "schema": {
              "$ref": "#/definitions/v1UpdateUserResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1UpdateUserRequest"
            }
          }
        ],
        "tags": [
          "User"
        ]
      }
    }
  },
  "definitions": {
    "GetCommentsByArticleResponseComment": {
      "type": "object",
      "properties": {
        "commentId": {
          "type": "string",
          "format": "uint64"
        },
        "content": {
          "type": "string"
        },
        "commenter": {
          "type": "string"
        },
        "usefulCount": {
          "type": "string",
          "format": "uint64"
        },
        "uselessCount": {
          "type": "string",
          "format": "uint64"
        },
        "createdAt": {
          "type": "string",
          "format": "int64"
        },
        "updatedAt": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "SearchUsersResponseUser": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        },
        "introduction": {
          "type": "string"
        },
        "profileInfo": {
          "type": "string"
        },
        "createdAt": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    },
    "v1AddTagsRequest": {
      "type": "object",
      "properties": {
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "TODO: This operation should be protected by a security mechanism. e.g, only privilege user can do this."
    },
    "v1AddTagsResponse": {
      "type": "object"
    },
    "v1DeleteArticleRequest": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uint64"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "v1DeleteArticleResponse": {
      "type": "object"
    },
    "v1DeleteCommentRequest": {
      "type": "object",
      "properties": {
        "commentId": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "v1DeleteCommentResponse": {
      "type": "object"
    },
    "v1DeleteTagRequest": {
      "type": "object",
      "properties": {
        "tag": {
          "type": "string"
        }
      },
      "description": "TODO: This operation should be protected by a security mechanism. e.g, only privilege user can do this."
    },
    "v1DeleteTagResponse": {
      "type": "object"
    },
    "v1EditCommentRequest": {
      "type": "object",
      "properties": {
        "commentId": {
          "type": "string",
          "format": "uint64"
        },
        "content": {
          "type": "string"
        }
      }
    },
    "v1EditCommentResponse": {
      "type": "object"
    },
    "v1GetCommentsByArticleRequest": {
      "type": "object",
      "properties": {
        "articleId": {
          "type": "string",
          "format": "uint64"
        }
      },
      "title": "Comment start"
    },
    "v1GetCommentsByArticleResponse": {
      "type": "object",
      "properties": {
        "comments": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/GetCommentsByArticleResponseComment"
          }
        }
      }
    },
    "v1GetCurrentUserInfoResponse": {
      "type": "object",
      "format": "object",
      "example": {
        "code": 0,
        "message": "ok",
        "data": {
          "username": "m4n5ter",
          "email": "email",
          "avatar_url": "https://example.com/avatar.jpg",
          "introduction": "introduction",
          "profile_info": "{}"
        }
      },
      "properties": {
        "username": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        },
        "introduction": {
          "type": "string"
        },
        "profileInfo": {
          "type": "string"
        }
      },
      "description": "获取当前用户信息响应体"
    },
    "v1GetPresignedURLRequest": {
      "type": "object",
      "properties": {
        "objectKey": {
          "type": "string"
        },
        "contentType": {
          "type": "string"
        },
        "operation": {
          "type": "string"
        },
        "isPublic": {
          "type": "boolean"
        }
      },
      "title": "S3 start"
    },
    "v1GetPresignedURLResponse": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "formData": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "v1MacFields": {
      "type": "object",
      "properties": {
        "macId": {
          "type": "string"
        },
        "macKey": {
          "type": "string"
        },
        "macAlgorithm": {
          "type": "string"
        }
      }
    },
    "v1PingResponse": {
      "type": "object"
    },
    "v1PostArticleRequest": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "poster": {
          "type": "string"
        }
      }
    },
    "v1PostArticleResponse": {
      "type": "object",
      "properties": {
        "articleId": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "v1PostCommentRequest": {
      "type": "object",
      "properties": {
        "articleId": {
          "type": "string",
          "format": "uint64"
        },
        "content": {
          "type": "string"
        }
      }
    },
    "v1PostCommentResponse": {
      "type": "object",
      "properties": {
        "commentId": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "v1RefreshAllArticlesRequest": {
      "type": "object",
      "description": "TODO: This operation should be protected by a security mechanism. e.g, only privilege user can do this."
    },
    "v1RefreshAllArticlesResponse": {
      "type": "object"
    },
    "v1RefreshTokenRequest": {
      "type": "object",
      "properties": {
        "refreshToken": {
          "type": "string"
        }
      }
    },
    "v1RefreshTokenResponse": {
      "type": "object",
      "format": "object",
      "example": {
        "code": 0,
        "message": "ok",
        "data": {
          "auth": {
            "mac_id": "mac_id",
            "mac_key": "mac_key",
            "mac_algorithm": "mac_algorithm"
          },
          "refresh_token": "refresh_token"
        }
      },
      "properties": {
        "apiKey": {
          "type": "string"
        },
        "macFields": {
          "$ref": "#/definitions/v1MacFields"
        },
        "refreshToken": {
          "type": "string"
        },
        "tokenExpire": {
          "type": "string",
          "format": "int64"
        },
        "refreshTokenExpire": {
          "type": "string",
          "format": "int64"
        }
      },
      "description": "刷新令牌响应体"
    },
    "v1SearchUsersRequest": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "v1SearchUsersResponse": {
      "type": "object",
      "format": "object",
      "example": {
        "code": 0,
        "message": "ok",
        "data": {
          "users": [
            {
              "username": "m4n5ter",
              "email": "email",
              "avatar_url": "https://example.com/avatar.jpg",
              "introduction": "introduction",
              "profile_info": "{}"
            }
          ]
        }
      },
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/SearchUsersResponseUser"
          }
        }
      },
      "description": "搜索用户响应体"
    },
    "v1SignInRequest": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "v1SignInResponse": {
      "type": "object",
      "format": "object",
      "example": {
        "code": 0,
        "message": "ok",
        "data": {
          "username": "m4n5ter",
          "avatar_url": "https://example.com/avatar.jpg",
          "mac_id": "mac_id",
          "mac_key": "mac_key",
          "mac_algorithm": "mac_algorithm",
          "refresh_token": "refresh_token"
        }
      },
      "properties": {
        "username": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        },
        "apiKey": {
          "type": "string"
        },
        "macFields": {
          "$ref": "#/definitions/v1MacFields"
        },
        "refreshToken": {
          "type": "string"
        },
        "tokenExpire": {
          "type": "string",
          "format": "int64"
        },
        "refreshTokenExpire": {
          "type": "string",
          "format": "int64"
        }
      },
      "description": "用户登录响应体"
    },
    "v1SignUpRequest": {
      "type": "object",
      "format": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        },
        "introduction": {
          "type": "string"
        },
        "profileInfo": {
          "type": "string",
          "title": "Should be a valid JSON string"
        }
      },
      "description": "用户注册请求体",
      "required": [
        "username",
        "email",
        "password"
      ]
    },
    "v1SignUpResponse": {
      "type": "object",
      "format": "object",
      "example": {
        "code": 0,
        "message": "ok"
      },
      "description": "用户注册响应体"
    },
    "v1UpdateCommentUsefulnessRequest": {
      "type": "object",
      "properties": {
        "commentId": {
          "type": "string",
          "format": "uint64"
        },
        "useful": {
          "type": "boolean",
          "title": "true 表示增加 useful 数量，false 表示增加 useless 数量"
        }
      }
    },
    "v1UpdateCommentUsefulnessResponse": {
      "type": "object",
      "properties": {
        "usefulCount": {
          "type": "string",
          "format": "uint64"
        },
        "uselessCount": {
          "type": "string",
          "format": "uint64"
        }
      }
    },
    "v1UpdateUserRequest": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "avatarUrl": {
          "type": "string"
        },
        "introduction": {
          "type": "string"
        },
        "profileInfo": {
          "type": "string"
        }
      }
    },
    "v1UpdateUserResponse": {
      "type": "object",
      "format": "object",
      "example": {
        "code": 0,
        "message": "ok"
      },
      "description": "更新用户信息响应体"
    }
  },
  "securityDefinitions": {
    "brainrot security": {
      "type": "oauth2",
      "flow": "accessCode",
      "scopes": {
        "R": "只读",
        "RW": "读写",
        "W": "只写"
      }
    }
  }
}
